d
j "poop"
f "poop"
m (0) x1 
m (0) x2 
m (1920) x3 
m (1080) x4 
m "(100,100,100)" x5
m "filledcircle" x6 

m (0) x1
m (0) x2
m (26) x3
m "If this circle and square fills your screen, my screen detection code works! :D" x4
m "(255,255,255)" x5
m "text" x6

m (0) x1
m (1054) x2
m (26) x3
m "shhh dont tell me about my z clipping shhhhh" x4
m "(255,255,255)" x5
m "text" x6


m (0) x1
m (0) x2
m (1920) x3
m (1080) x4
m "(255,0,0)" x5
m "square" x6

j "poop"
e